---
title: "html_test"
author: "kmikulik"
date: "16 12 2021"
output: html_document
---

<script>
function myFunction() {
    var x = document.getElementById("myDIV");
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}

</script>


### Heading


#### Percentage of cells with positive Inf+EFZ gene signature score

11% of the Myeloid2 cells have a positive score for the Inf+EFZ gene
signature (17 out of 145 cells).

On the other hand, only 4% of the Myeloid2 cells have a positive score 
for the Uninf+EFZ gene signature. ???
 
https://chrisbeeley.net/?p=1104


<button onclick="myFunction()">*Click here for details on integration*</button>
 
<div id="myDIV">

```
hiv7 <- readRDS("/media/ag-cherrmann/kmikulik/HIV_microglia/src/Reproduce_Farhadian_Paper/Seurat_objects/total_7_samples_label_transfer.rds")
hiv7 <- NormalizeData(hiv7, verbose = FALSE)
hiv7 <- FindVariableFeatures(hiv7, verbose = FALSE)

# add both datasets to a lits
data_list <- list(hiv = hiv7, triculture = triculture_clean)

# select features that are repeatedly variable across datasets for integration
features <- SelectIntegrationFeatures(object.list = data_list, verbose = FALSE)

# identify integration anchors and perform integration
anchors <- FindIntegrationAnchors(object.list = data_list, 
                                  anchor.features = features, verbose = FALSE) 
combined <- IntegrateData(anchorset = anchors, verbose = FALSE)

# run analysis on integrated dataset
combined <- ScaleData(combined, verbose = FALSE)
combined <- RunPCA(combined, verbose = FALSE)
#ElbowPlot(combined)
combined <- RunTSNE(combined, reduction = "pca", dims = 1:10, verbose = FALSE)
combined <- FindNeighbors(combined, reduction = "pca", dims = 1:10, verbose = FALSE)
combined <- FindClusters(combined, resolution = .3, verbose = FALSE)

# add annotations from which dataset the sample came from
dataset_vector <- (combined@meta.data %>% mutate(dataset = ifelse(orig.ident %in%
                                                 c("HIV1_CSF", "HIV2_CSF",
                                                   "HIV3_CSF", "HIV1_Bld", 
                                                   "HIV2_Bld", "Uninfected1_CSF",
                                                   "Uninfected2_CSF"),
                                               "csf", "triculture")))[["dataset"]]

combined <- AddMetaData(combined, dataset_vector, col.name = "dataset")

# add information on the cell groups in the combined datasets
combined_clusters <- (combined@meta.data %>% 
  mutate(combined_clusters = ifelse(seurat_clusters %in% c(2,10), "Microglia", 
                            ifelse(seurat_clusters %in% c(3,9), "iAst", 
                                   ifelse(seurat_clusters %in% c(0,1,7,11),
                                          "iNeurons", 
                                          ifelse(seurat_clusters %in% c(8,5,6), "Immune Cells", "Undesignated"))))))[["combined_clusters"]]
  
combined <- AddMetaData(combined, combined_clusters, col.name = "combined_clusters")

#saveRDS(combined,"/media/ag-cherrmann/kmikulik/HIV_microglia/src/Triculture_dataset_Ryan_paper/triculture_hiv_combined_seurat_object")

```
---
</div>


## Heading {.tabset}

TESTEaksdövjaäbnälg

### Tcell


### B cell

```{r}
hist(1:10)

```

## {-}

# Heading1


<details> 
  <summary>Click to Expand</summary>
  
**Human Immunodeficiency Virus (HIV)**

HIV is a lentivirus consisting of two single stranded RNA molecules, encoding 
fifteen different viral proteins which are essential for viral replication 
[@Osborne]. At the same time these proteins are potential targets for ART drugs.
The RNA molecules are enclosed in a capsid of p24 protein and the capsid is 
surrounded by a lipid membrane [@Osborne]. The viral envelope glycoprotein (Env)
is responsible for recognizing the host cells and the subsequent fusion of the 
vius with the host cell plasma membrane [@Huarte]. The glycoprotein gp120 binds
to the cluster of differentiation 4 (CD4) receptors on CD4+ T cells, macrophages
and microglia cells [@Osborne]. A structure of the virus particle is shown in 
figure 1 from [@Osborne].

---
</details> 

